export const MAIN = {
  FETCH_MESSAGES_SUCCESS: 'MAIN.FETCH_MESSAGES_SUCCESS',
  CREATE_MESSAGE_SUCCESS: 'MAIN.CREATE_MESSAGE_SUCCESS',
  UPDATE_MESSAGE_SUCCESS: 'MAIN.UPDATE_MESSAGE_SUCCESS',
  DELETE_MESSAGE_SUCCESS: 'MAIN.DELETE_MESSAGE_SUCCESS',
};